# Generated by Django 5.2.1 on 2025-05-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.desarrollador')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='catalogo.juego')),
            ],
        ),
    ]
